### ISSUE TITLE
Logout issue - different devices/browsers force logout

### ISSUE THREAD

**Issue by autistichoya** [RolePlayGateway/roleplaygateway#288] opened 2020-05-19 03:24 UTC
I'm using two devices right now. When I logged into the site from a device I hadn't used before, it logged me out on the other device (where I'd been logged in for a while).

**Comment by martindale** [comment] 2020-06-23 04:12
Good info, but duplicate of #192.

**Closed as completed by martindale** 2020-06-23 04:12 UTC
