### ISSUE TITLE
Keep Me Logged In broken

### ISSUE THREAD

**Issue by Lady-Awinita** [RolePlayGateway/roleplaygateway#202] opened 2019-12-17 07:50 UTC
The site will not keep me logged in when visiting places I own, or trying to navigate to the forums or anywhere else until I log back in at least twice. This is now more of an annoyance than ever that the checkbox for Keep Me Logged In no longer works.

I have the latest version of Chrome

EDIT: On recommendation of Law I attempted a different browser {Tor} and when pressing ADD POST I was once more logged out and forced to log in in order to post

EDIT 2: This *normally* happens during the time slots of 5-7PM eastern, and 12-4 am eastern NORMALLY, just the last 20 minutes I got logged out twice trying to view my notifications. Again using Chrome, this also occurs on Tor browser

EDIT 3: Just tried to view a thread in the help forum, and was logged out

EDIT 4: Just now got logged out going from Notifications page to my Character Management page

**Comment by lostamongtrees** [comment] 2019-12-17 17:57
Awi also noticed a correlation between the cookies and the logging in and out

**Comment by Lady-Awinita** [comment] 2019-12-17 21:21
> Awi also noticed a **correlation between the cookies and the logging in** and out

Can confirm that Law noticed this fact too

**Comment by Lady-Awinita** [comment] 2019-12-18 10:14
I am not sure if I shiould keep editing, so I will just announce it here, going from my medals list to my character management just this moment {5:12 am} logged me out enroute to my character management panel. Something is getting lost in navigation of the site and its both cookies and session data me thinks

NOTE: the only tabs I have open for RPG is RPG Chat, and the site itself
NOTE 2: This also occurs in another browser {Tor}
NOTE 3: I am most likely going to have too many comments reporting being logged out when trying to do anything on the site. I know for a fact this is not JUST ME having this issue, but I know for a fact that I am the only person most vocal about it, in a sense

**Comment by martindale** [comment] 2019-12-19 23:25
Might be related to #195.

**Comment by Lady-Awinita** [comment] 2019-12-23 03:29
OK so, this was really weird for me just now, Not only did an image link break {but I fixed it it just needed a new link!} but I also got logged out when editing a place to fix a broken image link. HOWEVER upon logging back invia the logon page directly it redirected me to the main front page instead of the forums.

THE GOOD NEWS IS: Tagging characters in posts without manually typing the names in once more works. but random logouts are expected so I guess that's good

**Comment by partially-stars** [comment] 2020-01-03 18:02
I've noticed this issue when trying to submit characters, editing characters, attempting to post, tagging characters, just browsing the site, basically doing anything ever. However, I seemed to get logged out less when I'm using Safari on my iPad or phone? Worsens if i have multiple tabs open.

**Comment by martindale** [comment] 2020-01-03 19:54
Thanks @partially-stars, super helpful.  I'm closing this as a duplicate of #192, where we're collecting a list of cases where this happens — I'm copying your reports over there now, where we'll continue troubleshooting.

**Closed as completed by martindale** 2020-01-03 19:54 UTC
Labels: bug, accessibility, good first issue
